server:
  port: 9004

spring:
  application:
    name: train12306-pay${unique-name:}-service
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      password: nacos
      username: nacos
    sentinel:
      transport:
        dashboard: localhost:8686
        port: 8719
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 3354054116

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: train12306_pay-service_common-message-execute_pg
    send-message-timeout: 2000
    retry-times-when-send-failed: 1
    retry-times-when-send-async-failed: 1

pay:
  alipay:
    alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAueg3vtGQxvikBgf8YU8doJvpj3bwFNhpDQJYJpJ5ZuwG0pCH8UoRJhax4AXmqfAbRm+KdMBh8V/Wl1yFvtFUA4NoZhm9Sqye8j4V83fV0+De9VRopBe7gOs9wsyRZa6CQKi2y6pIqaIm5I0eBFxSAR17RPG+FnOQrWOKH13f/7VfPCwpYL7z5kRdZdHWgTeykja/9YY3M5LXowajEaDn2jOB9+fLUwLv88VYVSw1Jan2m8NkK8QnZvb98FQmwKFoNEwNlhIlDvQzRMWcId8QrlZt65GrlV7TAUjtxiJWUi5UtHVWa4F6T0NZwl6PrK19rOQr5jGUK0yr+Q99Kh5eeQIDAQAB
    app-id: 2021000122637271
    charset: UTF8
    format: json
    notify-url: http://s4f28f26.natappfree.cc/api/pay-service/callback/alipay
    private-key: MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCeKVGVztp6wfe6RT7Cl+VClhhJYvKfg8WD50NdBza/g5A+C+5pNxADdd5Wsh8ckogaHh8RJ8XHO49Ydmd2Xa2DnyVFqrg67rr8OKRAoT4A8USXK5a5Qcrm0xh79Wrzwc3XoS7bhSeeiht7xHuW7Osz23Bxy659hq3EpCMc/m1Kbg+8u1GVRQApXurbWLLf1/Wnz3lj5H0drcy6Wpk8wRb1TWwnIUveq3sQbEuHCz6r7xRaAiTn6ljVebrahsExp3SYjdclIIwOTPR1GcXRS+6G8CPDk50WRAyAtKiB5K9QJPP/GzNSPFXkCT8PvjOEICYDxjE1sPZAdq2esI9b17n/AgMBAAECggEBAJTbDIczbVtWDYLJwzzAWyzlOSxwrStGiPIRCcyXioaLG4naDuQFx9OJ7t2nvTJWEzSJnvG1fiZ6PvqiTdQQbMtRUHIWMFh+8YuK/8Q4PbQDX2vrwWrQqle+2+9m1udeQw6sC/7dfqFvGFjPXwZ4KxHeeSEQ80P/KrLFTKrwJwqBtr1n83ZmSP5Op85nX2JDYqW2a9RtAeAWYZQcGuXl0i8v5bnkVifqr5jwiXgDg9ADIZye9+HD7PTaLyMpWHXVEjTbrt/PGqEOJ3pC4zDwCX23kJTOX2ta6XZ89ev/qkAoHMMUkT6hMpghNh3I/NUjNbotLUZ01G8dqgiqKK5hAEECgYEA6iBXdYQntMJnj5uXmu6gW3VQAGNGF8nD6zZzuWDD2TsEkNFFiGjDNED9MU7KiF46ILO8YozEO4Mpj/4ZE9pvYZpUqiyTQcAuO2pLCgF2TvT3uYRmJ5JDQZZ1icOnL8/mLQE0pRqgyMEaWxxggQTVj39+7GnI5Ky23ECvyYwjn+ECgYEArPAayulvAob6yMCqHzxqNEerNQpcQQYiYJs5ZHS0MJiHdzmLVC3qVlNz/Wjct7M1fJSAla6xXHVIom+4MMlve1A15eGL4acJ7msqYn8KxooI240BfSlqVnUpkuARTb8yYFTIjzEV5T5gVxlXc9esdXLwP/Z8IlhNilxrwXryFd8CgYEA5ozikv6Iex/VCz2UlSTXFDj5hug7ZcFyBHWij7ISKiBL5q+tYR6I2zQEIEIOfysK4pkbsZAczN3kV79IwpwfgmWPaeRrPhwZarjJHBlEf4wLRcxzLBSD1lprdDYOtK5tY3QEe3E1U3uUkJPpFCPGiYBrZDLneQf7KfkpIbe2fQECgYAQDpceQgBZprjATQs+rThbNFBUM2sPaodkmuUAS8mzPWZOjpw+K6k3bLY3UDY2JECSGaO6wiabpBQjaOYcOYfNVkw61O9M+1pztaWQ0aTpfEWIRRZfTaoe7u/2QDG7G0aNJTIeAXu79kexrputGNhda1edSMCL29EPSLeElmrF1wKBgQCt9HGxwdSjnVbZsH90SDFrUTdJOQcLhTnpv2HgZSDUlBz+mlYiIFimRliivVVZmhcGpH/6sYBKzEoMauXCVYFP84mlDILCfch1xwndxY88pBQ0HUszVGkyVZd9v0OiCYk93sW6YwatzvktHYGDICLeuYCYqBlXisrWu7dwSHdq1Q==
    server-url: https://openapi-sandbox.dl.alipaydev.com/gateway.do
    sign-type: RSA2

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mapper-locations: classpath:mapper/*.xml

framework:
  fastjson:
    safa-mode: true
  cache:
    redis:
      value-timeout: 16
      value-time-unit: days

management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}

remote:
  order:
    url: 127.0.0.1:9003